language: php

php:
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  # Initialise Composer
  - composer global require hirak/prestissimo

  # Installing Composer dependencies
  - composer update --no-interaction --ignore-platform-reqs --no-suggest --optimize-autoloader --ignore-platform-reqs

  # Installing code coverage tools
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer run security
  - vendor/bin/phpunit --testdox --coverage-clover clover.xml

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT
