name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  security:
    name: Security
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0 ] # Note: This workflow requires only the LATEST version of PHP
        os: [ ubuntu-latest ]

    steps: # General Steps
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v2

      # Install PHP Dependencies
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Validate Composer
        run: composer validate
      - name: Get Composer Cache Directory
        # Docs: <https://github.com/actions/cache/blob/master/examples.md#php---composer>
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Restore Composer Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-
      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      # Execution
      - name: Security Advisories
        run: composer require --dev roave/security-advisories:dev-latest

  static-analysis:
    name: Psalm
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0 ] # Note: This workflow requires only the LATEST version of PHP
        os: [ ubuntu-latest ]

    steps: # General Steps
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v2

      # Install PHP Dependencies
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Validate Composer
        run: composer validate
      - name: Get Composer Cache Directory
        # Docs: <https://github.com/actions/cache/blob/master/examples.md#php---composer>
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Restore Composer Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-
      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      # Execution
      - name: Static Analysis
        continue-on-error: true
        run: vendor/bin/psalm --no-cache

  coding-standards:
    name: Coding Standards
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0 ] # Note: This workflow requires only the LATEST version of PHP
        os: [ ubuntu-latest ]

    steps: # General Steps
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v2

      # Install PHP Dependencies
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Validate Composer
        run: composer validate
      - name: Get Composer Cache Directory
        # Docs: <https://github.com/actions/cache/blob/master/examples.md#php---composer>
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Restore Composer Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-
      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      # Execution
      - name: Check Coding Standards
        run: vendor/bin/phpcs --standard=phpcs.xml

  #
  # Execute unit tests on all valid PHP versions.
  #
  test:
    name: Build (${{matrix.php}}, ${{ matrix.os }}, ${{ matrix.stability }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0, 8.1 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        stability: [ prefer-lowest, prefer-stable ]

    steps: # General Steps
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v2

      # Install PHP Dependencies
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          extensions: pdo, pdo_mysql, pdo_sqlite, sockets
          coverage: pcov
          tools: pecl
          ini-values: "memory_limit=-1"
      - name: Validate Composer
        run: composer validate
      - name: Get Composer Cache Directory
        # Docs: <https://github.com/actions/cache/blob/master/examples.md#php---composer>
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Restore Composer Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-
      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      # Execution
      - name: Execute Tests
        run: vendor/bin/phpunit

  subsplit:
    name: Split (${{ matrix.package.local_path }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'Buffer'
            split_repository: 'buffer'
          - local_path: 'Compiler'
            split_repository: 'compiler'
          - local_path: 'Exception'
            split_repository: 'exception'
          - local_path: 'Grammar'
            split_repository: 'grammar'
          - local_path: 'Lexer'
            split_repository: 'lexer'
          - local_path: 'Parser'
            split_repository: 'parser'
          - local_path: 'Position'
            split_repository: 'position'
          - local_path: 'Source'
            split_repository: 'source'
          - local_path: 'Visitor'
            split_repository: 'visitor'
          - local_path: 'Contracts/Ast'
            split_repository: 'ast-contracts'
          - local_path: 'Contracts/Buffer'
            split_repository: 'buffer-contracts'
          - local_path: 'Contracts/Grammar'
            split_repository: 'grammar-contracts'
          - local_path: 'Contracts/Lexer'
            split_repository: 'lexer-contracts'
          - local_path: 'Contracts/Parser'
            split_repository: 'parser-contracts'
          - local_path: 'Contracts/Position'
            split_repository: 'position-contracts'
          - local_path: 'Contracts/Source'
            split_repository: 'source-contracts'
          - local_path: 'Meta/Runtime'
            split_repository: 'runtime'
          - local_path: 'Meta/Contracts'
            split_repository: 'contracts'

    steps:
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package.split_repository }}
        uses: symplify/github-action-monorepo-split@2.0
        with:
          package-directory: 'src/${{ matrix.package.local_path }}'
          split-repository-organization: 'phplrt'
          split-repository-name: '${{ matrix.package.split_repository }}'
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "master"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@2.0
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package-directory: 'src/${{ matrix.package.local_path }}'
          split-repository-organization: 'phplrt'
          split-repository-name: '${{ matrix.package.split_repository }}'
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "master"
